### ISSUE TITLE
typo  Laravel 7.x アップグレードガイド

### ISSUE THREAD

**Issue by KazutakaYamane** [laravel-ja/ja-docs-7.x#1]
https://readouble.com/laravel/7.x/ja/upgrade.html

-  リソース
Illuminate\Http\Resources\Json\JsonResourceを**拡張子**てください。
「拡張してください。」のタイポです。

訳文の公開、管理いつもありがとうございます。

**Comment by HiroKws** [comment]
ありがとうございます。修正しました。
