### ISSUE TITLE
「カスタムポリモーフィックタイプ」節 誤訳

### ISSUE THREAD

**Issue by toh-karashi** [laravel-ja/ja-docs-7.x#11]
Eloquent: Relationships - Laravel - The PHP Framework For Web Artisans : https://laravel.com/docs/7.x/eloquent-relationships#custom-polymorphic-types
Eloquent：リレーション 7.x Laravel : https://readouble.com/laravel/7.x/ja/eloquent-relationships.html

> You may determine the morph alias of a given model at runtime using the getMorphClass method. Conversely, you may determine the fully-qualified class name associated with a morph alias using the Relation::getMorphedModel method:

> getMorphClassメソッドを使用すると、実行時に指定モデルのmorph別名を決められます。逆に、Relation::getMorphedModelメソッドを使い、morph別名に関連付けている完全なクラス名を決めることもできます。

ここでの `determine` は「決める」ではなく「調べる」の意だと考えられます。
DETERMINE | meaning in the Cambridge English Dictionary : https://dictionary.cambridge.org/dictionary/english/determine

```
to discover the facts or truth about something:
The police never actually determined the cause of death.
[ + question word ] It is the responsibility of the court to determine whether these men are innocent.
[ + that ] The jury determined that the men were guilty.
```

**Comment by HiroKws** [comment]
ありがとうございます。修正しました。
