### ISSUE TITLE
Sanctumドキュメント内の軽微なミスの修正

### ISSUE THREAD

**Issue by toshikisugiyama** [laravel-ja/ja-docs-7.x#12]
https://readouble.com/laravel/7.x/ja/sanctum.html#how-it-works

`Tip!!` 内に

> APIトークン認証だけを使う場合、もしくはAPIトークン認証だけを使う場合のどちらにもSanctumは適しています。Sanctumが２つの機能を提供しているからといって、両方共に使う必要はありません。

とあります。

`APIトークン認証だけを使う場合` が2回書かれているので片方は `SPA認証だけを使う場合` だと思います。

[原文](https://laravel.com/docs/master/sanctum#how-it-works)は

> It is perfectly fine to use Sanctum only for API token authentication or only for SPA authentication. Just because you use Sanctum does not mean you are required to use both features it offers.

で `only for API token authentication` と `only for SPA authentication` になっています。

**Comment by HiroKws** [comment]
ありがとうございます。修正しました。
