### ISSUE TITLE
ドキュメント章別ページのAPIドキュメントのURLが誤っています

### ISSUE THREAD

**Issue by potetodog** [laravel-ja/ja-docs-7.x#4]
誤：https://readouble.com/laravel/7.x/ja/7.x.html
正：https://laravel.com/api/7.x/

**Comment by HiroKws** [comment]
変換プログラムを修正する必用があるためしばらく時間をいただきます。原因はオリジナル英文のリンク形式がフルURLから相対URIへ変わってしまったためです。

**Comment by HiroKws** [comment]
修正しました。このリポジトリで扱う翻訳文ではなく、変換プログラムの修正のため、当リポジトリに影響はありません。
